### ISSUE TITLE
caffe model result is not equal pytorch model result

### ISSUE THREAD

**Issue by rainfalj** [starimeL/PytorchConverter#11]
For a same picture When using a 8 classes ResNet18 model, caffe model outputs[-0.54072326  3.41359568  8.56874561 -0.82260311 -2.66256571 -2.29306793 -2.2721777  -3.39299512], pytorch model outputs [-2.31570864  3.20797634  9.79750538 -0.47102225 -2.78121352 -1.77155793 -1.88433588 -3.78068781].

**Comment by starimeL** [comment]
The most possible reason causing such difference seems to be pixel normalization difference or BGR channel swapped. To make sure you feed exactly the same tensor input to pytorch and caffe, you can refer to /code/test.py.
