### ISSUE TITLE
ValueError: Unknown layer type: Scatter

### ISSUE THREAD

**Issue by zhly0** [starimeL/PytorchConverter#3]
Thanks for your code!
but when converting pytorch model to caffe ,it has this error:
ValueError: Unknown layer type: Scatter,is this a broadcast operation?

**Comment by starimeL** [comment]
It might be a specific layer or operation function haven't been supported yet.
You can find out and tell me the function, I will try to support that

**Comment by zhly0** [comment]
Thanks for reply,and this scatter is not a layer,just a broadcast operation.

**Comment by zcl912** [comment]
> Thanks for reply,and this scatter is not a layer,just a broadcast operation.

hello , i met the problem too, how to solve it? thx
