### ISSUE TITLE
Slice

### ISSUE THREAD

**Issue by zhly0** [starimeL/PytorchConverter#8]
Tanks for your code,and I think there is something not so right in The slice  operation,image I have a 
intput shape is 1x1x128x128,and followed but a channel num=96 ,kernel size 5 convolution,then a slice operation,then add the sliced two part together,but the slice operation I converted like:
Input            data             0 1 data 0=1 1=128 2=128
Convolution      ConvNd_1         1 1 data ConvNd_1 0=96 1=5 2=1 3=1 4=2 5=1 6=2400
Split            splitncnn_1      1 2 ConvNd_1 splitncnn_Index_1 splitncnn_Index_2
Slice            splitncnn_Index_2_slicer 1 1 splitncnn_Index_2 splitncnn_Index_2_Index_2 0=2 1=48 2=-233
Eltwise          Cmax_1           2 1 splitncnn_Index_1_Index_1 splitncnn_Index_2_Index_2 Cmax_1 0=2
the splitncnn_Index_2_slicer has just one output,but it should have two,and the Cmax_1 layer should add two output of Slice,but it not.is there something wrong with slice layer?

**Comment by starimeL** [comment]
The latest commit has totally fixed these kind of problems I guess.
Please have a try on your result and see if it's correct.

**Comment by zhly0** [comment]
@starimeL  Thanks! I will try!
